spring.datasource.url=jdbc:mysql://127.0.0.1:3306/salon_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=root

# Datos de Google (usa los que tengas de tu consola de desarrollador)
google.client.id=89387125120-8evcs88o8g0kk6pfnv41p7iiggofk2n3.apps.googleusercontent.com
google.client.secret=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

# Configuración para el Admin Server
spring.boot.admin.client.url=http://localhost:9090
management.endpoints.web.exposure.include=*